import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals/globals.css';
import '../globals/tailwind.css';
import { MiddlewareInit } from '@/core/middlewares';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await MiddlewareInit();

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
